---
- name: Wait 10 seconds
  ansible.builtin.wait_for:
    timeout: 10

- name: Copy js script
  become: true
  ansible.builtin.template:
    src: configReplSet.js.j2
    dest: /etc/configReplSet.js
    mode: '0644'
  tags:
    - mongo
    - replication

- name: Create replica configReplSet
  community.mongodb.mongodb_shell:
    login_host: "{{ host01 }}"
    login_port: 27019
    login_user: "{{ mongodb_user }}"
    login_password: "{{ mongodb_pass }}"
    login_database: "{{ mongo_database }}"
    file: /etc/configReplSet.js
    idempotent: true
  tags:
    - mongo
    - replication
...
