---
- name: Check SELinux status
  become: true
  ansible.builtin.lineinfile:
    dest: "/etc/selinux/config"
    line: "SELINUX=enforcing"
  check_mode: true
  register: sestate
  tags:
    - mongo
    - pretasks

- name: Disable SELinux
  become: true
  ansible.builtin.replace:
    path: "/etc/selinux/config"
    regexp: SELINUX=enforcing
    replace: SELINUX=disabled
  notify:
    - Setenforce
  when: not sestate.changed
  tags:
    - mongo
    - pretasks

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
  tags:
    - mongo
    - pretasks

- name: Stop Firewalld
  become: true
  ansible.builtin.systemd:
    name: firewalld
    enabled: false
    masked: true
    state: stopped
  tags:
    - mongo
    - pretasks

- name: Edit /etc/profile
  become: true
  ansible.builtin.blockinfile:
    path: /etc/profile
    block: |
      shopt -s histappend
      export HISTSIZE=10000
      export HISTTIMEFORMAT="%h %d %H:%M:%S "
      PROMPT_COMMAND='history -a'
      export HISTIGNORE="ls:ll:history:w:htop:pwd"
  tags:
    - mongo
    - pretasks

- name: Add Mongo Repo
  become: true
  ansible.builtin.template:
    src: mongodb.repo.j2
    dest: /etc/yum.repos.d/mongodb.repo
    mode: '0644'
  tags:
    - mongo
    - pretasks

- name: Upgrade all packages
  become: true
  ansible.builtin.yum:
    name: '*'
    state: latest
  tags:
    - mongo
    - pretasks

- name: Install Packages
  become: true
  ansible.builtin.yum:
    name:
      - nano
      - sysstat
      - mlocate
      - net-tools
      - bind-utils
      - tcpdump
      - curl
      - wget
      - mongodb-org
    state: present
  tags:
    - mongo
    - pretasks

- name: Rename Hosts
  become: true
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"
  tags:
    - mongo
    - pretasks

- name: Copy hosts file
  become: true
  ansible.builtin.template:
    src: hosts.j2
    dest: /etc/hosts
    mode: '0644'
  tags:
    - mongo
    - pretasks

- name: Upgrade pip
  become: true
  ansible.builtin.pip:
    name: pip
    extra_args: --upgrade
    executable: pip3
    state: latest
  tags:
    - mongo
    - pretasks

- name: Install libs
  become: true
  ansible.builtin.pip:
    name:
      - cryptography>=1.2.3
      - pymongo
      - selinux
    executable: pip3
    state: present
  tags:
    - mongo
    - pretasks
...
