---
- name: Replace storage path
  become: true
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: "dbPath: /var/lib/mongo"
    replace: "dbPath: /mongo"
  tags:
    - mongo
    - primary_shard

- name: Start mongod
  become: true
  ansible.builtin.systemd:
    name: mongod
    enabled: true
    masked: false
    state: started
  tags:
    - mongo
    - primary_shard

- name: Create admin user
  community.mongodb.mongodb_user:
    database: "{{ mongo_database }}"
    name: "{{ mongodb_user }}"
    password: "{{ mongodb_pass }}"
    state: present
    roles: "{{ mongodb_role }}"
  tags:
    - mongo
    - primary_shard
...
