---
- name: Copy mongodb config
  become: true
  ansible.builtin.template:
    src: mongodConfig.conf.j2
    dest: /etc/mongod.conf
    mode: '0644'
  notify:
    - Restart mongod
  tags:
    - mongo
    - replicas

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
  tags:
    - mongo
    - replicas
...
