---
- name: Stop mongod
  become: true
  ansible.builtin.systemd:
    name: mongod
    enabled: false
    masked: true
    state: stopped

- name: Copy mongodb config
  become: true
  ansible.builtin.template:
    src: mongoRouter.conf.j2
    dest: /etc/mongos.conf

- name: Copy systemd unit
  become: true
  ansible.builtin.template:
    src: mongos.service.j2
    dest: /etc/systemd/system/mongos.service

- name: Start mongos
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    name: mongos
    enabled: true
    masked: false
    state: started

- name: Copy js script
  become: true
  ansible.builtin.template:
    src: addShard.js.j2
    dest: /etc/addShard.js

- name: Add shards
  community.mongodb.mongodb_shell:
    login_host: "{{ ip07 }}"
    login_port: 27017
    login_user: "{{ mongodb_user }}"
    login_password: "{{ mongodb_pass }}"
    login_database: "{{ mongo_database }}"
    file: "/etc/addShard.js"
    idempotent: true
...
