---
- name: Stop mongod
  become: true
  ansible.builtin.systemd:
    name: mongod
    enabled: false
    masked: true
    state: stopped
  tags:
    - router

- name: Copy mongodb config
  become: true
  ansible.builtin.template:
    src: mongoRouter.conf.j2
    dest: /etc/mongos.conf
    mode: '0644'
  tags:
    - router

- name: Copy systemd unit
  become: true
  ansible.builtin.template:
    src: mongos.service.j2
    dest: /etc/systemd/system/mongos.service
    mode: '0644'
  notify:
    - Start mongos
  tags:
    - router

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
  tags:
    - router

- name: Copy js script
  become: true
  ansible.builtin.template:
    src: addShard.js.j2
    dest: /etc/addShard.js
    mode: '0644'
  tags:
    - router

- name: Add shards
  community.mongodb.mongodb_shell:
    login_host: "{{ ip07 }}"
    login_port: 27017
    login_user: "{{ mongodb_user }}"
    login_password: "{{ mongodb_pass }}"
    login_database: "{{ mongo_database }}"
    file: "/etc/addShard.js"
    idempotent: true
  tags:
    - router
...
