---
- name: Mongo - Copy mongodb config
  become: true
  ansible.builtin.template:
    src: mongodShard.conf.j2
    dest: /etc/mongod.conf
    mode: '0644'
  notify:
    - Restart mongod
  tags:
    - mongo
    - shards_hosts

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
  tags:
    - mongo
    - shards_hosts
...
