- name: Device partitioning
  become: true
  parted:
    device: '{{ blockDevice }}'
    number: 1
    state: present
  tags:
    - mongo
    - xfs

- name: Create XFS FS
  become: true
  community.general.filesystem:
    fstype: xfs
    dev: '{{ partedDevice }}'
  tags:
    - mongo
    - xfs

- name: Create Directory
  become: true
  ansible.builtin.file:
    path: '{{ mongoDir }}'
    state: directory
    mode: '0755'
  tags:
    - mongo
    - xfs

- name: Update fstab
  become: true
  ansible.builtin.lineinfile:
    dest: /etc/fstab
    line: '{{ partedDevice }}  {{ mongoDir }}  xfs  defaults  0  0'
  tags:
    - mongo
    - xfs

- name: Monut XFS device
  become: true
  ansible.posix.mount:
    path: '{{ mongoDir }}'
    src: '{{ partedDevice }}'
    fstype: xfs
    state: mounted
  tags:
    - mongo
    - xfs

- name: Change Permissions
  become: true
  ansible.builtin.file:
    path: '{{ mongoDir }}'
    owner: mongod
    group: mongod
  tags:
    - mongo
    - xfs
...
