---

mongo_version: "5.0"
mongo_database: "CHANGEME"
mongodb_user: "CHANGEME"
mongodb_pass: "CHANGEME"
mongodb_role: "CHANGEME"
ip01: "CHANGEME"
ip02: "CHANGEME"
ip03: "CHANGEME"
ip04: "CHANGEME"
ip05: "CHANGEME"
ip06: "CHANGEME"
ip07: "CHANGEME"
